services:
  - type: web
    name: arogyam-backend
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRY
        value: 15m
      - key: REFRESH_TOKEN_EXPIRY
        value: 7d
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 4000
    # Expose the port that the application listens on
    expose:
      - 4000